// Copyright (c) Ultraviolet
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery v2.53.3. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Algorithm is an autogenerated mock type for the Algorithm type
type Algorithm struct {
	mock.Mock
}

type Algorithm_Expecter struct {
	mock *mock.Mock
}

func (_m *Algorithm) EXPECT() *Algorithm_Expecter {
	return &Algorithm_Expecter{mock: &_m.Mock}
}

// Run provides a mock function with no fields
func (_m *Algorithm) Run() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Algorithm_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type Algorithm_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
func (_e *Algorithm_Expecter) Run() *Algorithm_Run_Call {
	return &Algorithm_Run_Call{Call: _e.mock.On("Run")}
}

func (_c *Algorithm_Run_Call) Run(run func()) *Algorithm_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Algorithm_Run_Call) Return(_a0 error) *Algorithm_Run_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Algorithm_Run_Call) RunAndReturn(run func() error) *Algorithm_Run_Call {
	_c.Call.Return(run)
	return _c
}

// Stop provides a mock function with no fields
func (_m *Algorithm) Stop() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stop")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Algorithm_Stop_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stop'
type Algorithm_Stop_Call struct {
	*mock.Call
}

// Stop is a helper method to define mock.On call
func (_e *Algorithm_Expecter) Stop() *Algorithm_Stop_Call {
	return &Algorithm_Stop_Call{Call: _e.mock.On("Stop")}
}

func (_c *Algorithm_Stop_Call) Run(run func()) *Algorithm_Stop_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *Algorithm_Stop_Call) Return(_a0 error) *Algorithm_Stop_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *Algorithm_Stop_Call) RunAndReturn(run func() error) *Algorithm_Stop_Call {
	_c.Call.Return(run)
	return _c
}

// NewAlgorithm creates a new instance of Algorithm. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAlgorithm(t interface {
	mock.TestingT
	Cleanup(func())
}) *Algorithm {
	mock := &Algorithm{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
