version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - errcheck
    - errchkjson
    - errname
    - ginkgolinter
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godot
    - godox
    - goheader
    - goprintffuncname
    - govet
    - importas
    - ineffassign
    - loggercheck
    - makezero
    - mirror
    - misspell
    - nakedret
    - staticcheck
    - unused
    - whitespace
  settings:
    gocritic:
      enabled-checks:
        - dupImport
        - importShadow
        - httpNoBody
        - paramTypeCombine
        - emptyStringTest
        - builtinShadow
        - exposedSyncMutex
      disabled-checks:
        - appendAssign
      enabled-tags:
        - diagnostic
      disabled-tags:
        - performance
        - style
        - experimental
        - opinionated
    goheader:
      template: |-
        Copyright (c) Ultraviolet
        SPDX-License-Identifier: Apache-2.0
    staticcheck:
      checks:
        - -ST1000
        - -ST1003
        - -ST1020
        - -ST1021
        - -ST1022
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - makezero
        text: with non-zero initialized length
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 10
  max-same-issues: 10
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
