run:
  timeout: 3m

issues:
  max-issues-per-linter: 10
  max-same-issues: 10

linters-settings:
  importas:
    no-unaliased: true
    no-extra-aliases: false
    alias:
      - pkg: github.com/absmach/magistrala/logger
        alias: mglog

  gocritic:
    enabled-checks:
      - dupImport
      - importShadow
      - httpNoBody
      - paramTypeCombine
      - emptyStringTest
      - builtinShadow
      - exposedSyncMutex
    disabled-checks:
      - appendAssign
    enabled-tags:
      - diagnostic
    disabled-tags:
      - performance
      - style
      - experimental
      - opinionated
  stylecheck:
    checks: ["-ST1000", "-ST1003", "-ST1020", "-ST1021", "-ST1022"]
  goheader:
    template: |-
      Copyright (c) Ultraviolet
      SPDX-License-Identifier: Apache-2.0

linters:
  disable-all: true
  enable:
    - importas
    - gocritic
    - gosimple
    - errcheck
    - govet
    - unused
    - goconst
    - godot
    - godox
    - ineffassign
    - misspell
    - stylecheck
    - whitespace
    - gci
    - gofmt
    - goimports
    - loggercheck
    - goheader
    - asasalint
    - asciicheck
    - bidichk
    - contextcheck
    - decorder
    - dogsled
    - errchkjson
    - errname
    - copyloopvar
    - ginkgolinter
    - gocheckcompilerdirectives
    - gofumpt
    - goprintffuncname
    - importas
    - makezero
    - mirror
    - nakedret
    - dupword

