// Copyright (c) Ultraviolet
// SPDX-License-Identifier: Apache-2.0

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"github.com/ultravioletrs/cocos/agent/statemachine"
)

// NewStateMachine creates a new instance of StateMachine. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStateMachine(t interface {
	mock.TestingT
	Cleanup(func())
}) *StateMachine {
	mock := &StateMachine{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// StateMachine is an autogenerated mock type for the StateMachine type
type StateMachine struct {
	mock.Mock
}

type StateMachine_Expecter struct {
	mock *mock.Mock
}

func (_m *StateMachine) EXPECT() *StateMachine_Expecter {
	return &StateMachine_Expecter{mock: &_m.Mock}
}

// AddTransition provides a mock function for the type StateMachine
func (_mock *StateMachine) AddTransition(t statemachine.Transition) {
	_mock.Called(t)
	return
}

// StateMachine_AddTransition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddTransition'
type StateMachine_AddTransition_Call struct {
	*mock.Call
}

// AddTransition is a helper method to define mock.On call
//   - t statemachine.Transition
func (_e *StateMachine_Expecter) AddTransition(t interface{}) *StateMachine_AddTransition_Call {
	return &StateMachine_AddTransition_Call{Call: _e.mock.On("AddTransition", t)}
}

func (_c *StateMachine_AddTransition_Call) Run(run func(t statemachine.Transition)) *StateMachine_AddTransition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 statemachine.Transition
		if args[0] != nil {
			arg0 = args[0].(statemachine.Transition)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StateMachine_AddTransition_Call) Return() *StateMachine_AddTransition_Call {
	_c.Call.Return()
	return _c
}

func (_c *StateMachine_AddTransition_Call) RunAndReturn(run func(t statemachine.Transition)) *StateMachine_AddTransition_Call {
	_c.Run(run)
	return _c
}

// GetState provides a mock function for the type StateMachine
func (_mock *StateMachine) GetState() statemachine.State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 statemachine.State
	if returnFunc, ok := ret.Get(0).(func() statemachine.State); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(statemachine.State)
		}
	}
	return r0
}

// StateMachine_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type StateMachine_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *StateMachine_Expecter) GetState() *StateMachine_GetState_Call {
	return &StateMachine_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *StateMachine_GetState_Call) Run(run func()) *StateMachine_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *StateMachine_GetState_Call) Return(state statemachine.State) *StateMachine_GetState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *StateMachine_GetState_Call) RunAndReturn(run func() statemachine.State) *StateMachine_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type StateMachine
func (_mock *StateMachine) Reset(initialState statemachine.State) {
	_mock.Called(initialState)
	return
}

// StateMachine_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type StateMachine_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
//   - initialState statemachine.State
func (_e *StateMachine_Expecter) Reset(initialState interface{}) *StateMachine_Reset_Call {
	return &StateMachine_Reset_Call{Call: _e.mock.On("Reset", initialState)}
}

func (_c *StateMachine_Reset_Call) Run(run func(initialState statemachine.State)) *StateMachine_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 statemachine.State
		if args[0] != nil {
			arg0 = args[0].(statemachine.State)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StateMachine_Reset_Call) Return() *StateMachine_Reset_Call {
	_c.Call.Return()
	return _c
}

func (_c *StateMachine_Reset_Call) RunAndReturn(run func(initialState statemachine.State)) *StateMachine_Reset_Call {
	_c.Run(run)
	return _c
}

// SendEvent provides a mock function for the type StateMachine
func (_mock *StateMachine) SendEvent(event statemachine.Event) {
	_mock.Called(event)
	return
}

// StateMachine_SendEvent_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendEvent'
type StateMachine_SendEvent_Call struct {
	*mock.Call
}

// SendEvent is a helper method to define mock.On call
//   - event statemachine.Event
func (_e *StateMachine_Expecter) SendEvent(event interface{}) *StateMachine_SendEvent_Call {
	return &StateMachine_SendEvent_Call{Call: _e.mock.On("SendEvent", event)}
}

func (_c *StateMachine_SendEvent_Call) Run(run func(event statemachine.Event)) *StateMachine_SendEvent_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 statemachine.Event
		if args[0] != nil {
			arg0 = args[0].(statemachine.Event)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StateMachine_SendEvent_Call) Return() *StateMachine_SendEvent_Call {
	_c.Call.Return()
	return _c
}

func (_c *StateMachine_SendEvent_Call) RunAndReturn(run func(event statemachine.Event)) *StateMachine_SendEvent_Call {
	_c.Run(run)
	return _c
}

// SetAction provides a mock function for the type StateMachine
func (_mock *StateMachine) SetAction(state statemachine.State, action statemachine.Action) {
	_mock.Called(state, action)
	return
}

// StateMachine_SetAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAction'
type StateMachine_SetAction_Call struct {
	*mock.Call
}

// SetAction is a helper method to define mock.On call
//   - state statemachine.State
//   - action statemachine.Action
func (_e *StateMachine_Expecter) SetAction(state interface{}, action interface{}) *StateMachine_SetAction_Call {
	return &StateMachine_SetAction_Call{Call: _e.mock.On("SetAction", state, action)}
}

func (_c *StateMachine_SetAction_Call) Run(run func(state statemachine.State, action statemachine.Action)) *StateMachine_SetAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 statemachine.State
		if args[0] != nil {
			arg0 = args[0].(statemachine.State)
		}
		var arg1 statemachine.Action
		if args[1] != nil {
			arg1 = args[1].(statemachine.Action)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *StateMachine_SetAction_Call) Return() *StateMachine_SetAction_Call {
	_c.Call.Return()
	return _c
}

func (_c *StateMachine_SetAction_Call) RunAndReturn(run func(state statemachine.State, action statemachine.Action)) *StateMachine_SetAction_Call {
	_c.Run(run)
	return _c
}

// Start provides a mock function for the type StateMachine
func (_mock *StateMachine) Start(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// StateMachine_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type StateMachine_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *StateMachine_Expecter) Start(ctx interface{}) *StateMachine_Start_Call {
	return &StateMachine_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *StateMachine_Start_Call) Run(run func(ctx context.Context)) *StateMachine_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *StateMachine_Start_Call) Return(err error) *StateMachine_Start_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *StateMachine_Start_Call) RunAndReturn(run func(ctx context.Context) error) *StateMachine_Start_Call {
	_c.Call.Return(run)
	return _c
}
