// Copyright (c) Ultraviolet
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.33.1
// source: agent/runner/runner.proto

package runner

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComputationId string                 `protobuf:"bytes,1,opt,name=computation_id,json=computationId,proto3" json:"computation_id,omitempty"`
	AlgoType      string                 `protobuf:"bytes,2,opt,name=algo_type,json=algoType,proto3" json:"algo_type,omitempty"` // "binary", "python", "wasm", "docker"
	Algorithm     []byte                 `protobuf:"bytes,3,opt,name=algorithm,proto3" json:"algorithm,omitempty"`               // The algorithm binary/script content
	Requirements  []byte                 `protobuf:"bytes,4,opt,name=requirements,proto3" json:"requirements,omitempty"`         // Python requirements.txt content
	Args          []string               `protobuf:"bytes,5,rep,name=args,proto3" json:"args,omitempty"`
	Datasets      []*Dataset             `protobuf:"bytes,6,rep,name=datasets,proto3" json:"datasets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_agent_runner_runner_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runner_runner_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunRequest.ProtoReflect.Descriptor instead.
func (*RunRequest) Descriptor() ([]byte, []int) {
	return file_agent_runner_runner_proto_rawDescGZIP(), []int{0}
}

func (x *RunRequest) GetComputationId() string {
	if x != nil {
		return x.ComputationId
	}
	return ""
}

func (x *RunRequest) GetAlgoType() string {
	if x != nil {
		return x.AlgoType
	}
	return ""
}

func (x *RunRequest) GetAlgorithm() []byte {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *RunRequest) GetRequirements() []byte {
	if x != nil {
		return x.Requirements
	}
	return nil
}

func (x *RunRequest) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *RunRequest) GetDatasets() []*Dataset {
	if x != nil {
		return x.Datasets
	}
	return nil
}

type Dataset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Hash          []byte                 `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Dataset) Reset() {
	*x = Dataset{}
	mi := &file_agent_runner_runner_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Dataset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Dataset) ProtoMessage() {}

func (x *Dataset) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runner_runner_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Dataset.ProtoReflect.Descriptor instead.
func (*Dataset) Descriptor() ([]byte, []int) {
	return file_agent_runner_runner_proto_rawDescGZIP(), []int{1}
}

func (x *Dataset) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *Dataset) GetHash() []byte {
	if x != nil {
		return x.Hash
	}
	return nil
}

type RunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComputationId string                 `protobuf:"bytes,1,opt,name=computation_id,json=computationId,proto3" json:"computation_id,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_agent_runner_runner_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runner_runner_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunResponse.ProtoReflect.Descriptor instead.
func (*RunResponse) Descriptor() ([]byte, []int) {
	return file_agent_runner_runner_proto_rawDescGZIP(), []int{2}
}

func (x *RunResponse) GetComputationId() string {
	if x != nil {
		return x.ComputationId
	}
	return ""
}

func (x *RunResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StopRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ComputationId string                 `protobuf:"bytes,1,opt,name=computation_id,json=computationId,proto3" json:"computation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopRequest) Reset() {
	*x = StopRequest{}
	mi := &file_agent_runner_runner_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRequest) ProtoMessage() {}

func (x *StopRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_runner_runner_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRequest.ProtoReflect.Descriptor instead.
func (*StopRequest) Descriptor() ([]byte, []int) {
	return file_agent_runner_runner_proto_rawDescGZIP(), []int{3}
}

func (x *StopRequest) GetComputationId() string {
	if x != nil {
		return x.ComputationId
	}
	return ""
}

var File_agent_runner_runner_proto protoreflect.FileDescriptor

const file_agent_runner_runner_proto_rawDesc = "" +
	"\n" +
	"\x19agent/runner/runner.proto\x12\x06runner\x1a\x1bgoogle/protobuf/empty.proto\"\xd3\x01\n" +
	"\n" +
	"RunRequest\x12%\n" +
	"\x0ecomputation_id\x18\x01 \x01(\tR\rcomputationId\x12\x1b\n" +
	"\talgo_type\x18\x02 \x01(\tR\balgoType\x12\x1c\n" +
	"\talgorithm\x18\x03 \x01(\fR\talgorithm\x12\"\n" +
	"\frequirements\x18\x04 \x01(\fR\frequirements\x12\x12\n" +
	"\x04args\x18\x05 \x03(\tR\x04args\x12+\n" +
	"\bdatasets\x18\x06 \x03(\v2\x0f.runner.DatasetR\bdatasets\"9\n" +
	"\aDataset\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x12\n" +
	"\x04hash\x18\x02 \x01(\fR\x04hash\"J\n" +
	"\vRunResponse\x12%\n" +
	"\x0ecomputation_id\x18\x01 \x01(\tR\rcomputationId\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"4\n" +
	"\vStopRequest\x12%\n" +
	"\x0ecomputation_id\x18\x01 \x01(\tR\rcomputationId2x\n" +
	"\x11ComputationRunner\x12.\n" +
	"\x03Run\x12\x12.runner.RunRequest\x1a\x13.runner.RunResponse\x123\n" +
	"\x04Stop\x12\x13.runner.StopRequest\x1a\x16.google.protobuf.EmptyB\n" +
	"Z\b./runnerb\x06proto3"

var (
	file_agent_runner_runner_proto_rawDescOnce sync.Once
	file_agent_runner_runner_proto_rawDescData []byte
)

func file_agent_runner_runner_proto_rawDescGZIP() []byte {
	file_agent_runner_runner_proto_rawDescOnce.Do(func() {
		file_agent_runner_runner_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_runner_runner_proto_rawDesc), len(file_agent_runner_runner_proto_rawDesc)))
	})
	return file_agent_runner_runner_proto_rawDescData
}

var file_agent_runner_runner_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_agent_runner_runner_proto_goTypes = []any{
	(*RunRequest)(nil),    // 0: runner.RunRequest
	(*Dataset)(nil),       // 1: runner.Dataset
	(*RunResponse)(nil),   // 2: runner.RunResponse
	(*StopRequest)(nil),   // 3: runner.StopRequest
	(*emptypb.Empty)(nil), // 4: google.protobuf.Empty
}
var file_agent_runner_runner_proto_depIdxs = []int32{
	1, // 0: runner.RunRequest.datasets:type_name -> runner.Dataset
	0, // 1: runner.ComputationRunner.Run:input_type -> runner.RunRequest
	3, // 2: runner.ComputationRunner.Stop:input_type -> runner.StopRequest
	2, // 3: runner.ComputationRunner.Run:output_type -> runner.RunResponse
	4, // 4: runner.ComputationRunner.Stop:output_type -> google.protobuf.Empty
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_agent_runner_runner_proto_init() }
func file_agent_runner_runner_proto_init() {
	if File_agent_runner_runner_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_runner_runner_proto_rawDesc), len(file_agent_runner_runner_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_runner_runner_proto_goTypes,
		DependencyIndexes: file_agent_runner_runner_proto_depIdxs,
		MessageInfos:      file_agent_runner_runner_proto_msgTypes,
	}.Build()
	File_agent_runner_runner_proto = out.File
	file_agent_runner_runner_proto_goTypes = nil
	file_agent_runner_runner_proto_depIdxs = nil
}
