// Code generated by "stringer -type=AgentState"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-0]
	_ = x[ReceivingManifest-1]
	_ = x[ReceivingAlgorithm-2]
	_ = x[ReceivingData-3]
	_ = x[Running-4]
	_ = x[ConsumingResults-5]
	_ = x[Complete-6]
	_ = x[Failed-7]
}

const _AgentState_name = "IdleReceivingManifestReceivingAlgorithmReceivingDataRunningConsumingResultsCompleteFailed"

var _AgentState_index = [...]uint8{0, 4, 21, 39, 52, 59, 75, 83, 89}

func (i AgentState) String() string {
	if i < 0 || i >= AgentState(len(_AgentState_index)-1) {
		return "AgentState(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AgentState_name[_AgentState_index[i]:_AgentState_index[i+1]]
}
