// Code generated by "stringer -type=State"; DO NOT EDIT.

package agent

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Idle-0]
	_ = x[ReceivingManifest-1]
	_ = x[ReceivingAlgorithm-2]
	_ = x[ReceivingData-3]
	_ = x[Running-4]
	_ = x[ResultFetch-5]
	_ = x[Complete-6]
	_ = x[Failed-7]
}

const _State_name = "IdleReceivingManifestReceivingAlgorithmReceivingDataRunningResultFetchCompleteFailed"

var _State_index = [...]uint8{0, 4, 21, 39, 52, 59, 70, 78, 84}

func (i State) String() string {
	if i >= State(len(_State_index)-1) {
		return "State(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _State_name[_State_index[i]:_State_index[i+1]]
}
