// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.1
// source: internal/proto/attestation-agent/attestation-agent.proto

package attestation_agent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AttestationAgentService_GetEvidence_FullMethodName              = "/attestation_agent.AttestationAgentService/GetEvidence"
	AttestationAgentService_GetAdditionalEvidence_FullMethodName    = "/attestation_agent.AttestationAgentService/GetAdditionalEvidence"
	AttestationAgentService_GetToken_FullMethodName                 = "/attestation_agent.AttestationAgentService/GetToken"
	AttestationAgentService_ExtendRuntimeMeasurement_FullMethodName = "/attestation_agent.AttestationAgentService/ExtendRuntimeMeasurement"
	AttestationAgentService_BindInitData_FullMethodName             = "/attestation_agent.AttestationAgentService/BindInitData"
	AttestationAgentService_GetTeeType_FullMethodName               = "/attestation_agent.AttestationAgentService/GetTeeType"
)

// AttestationAgentServiceClient is the client API for AttestationAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AttestationAgentServiceClient interface {
	GetEvidence(ctx context.Context, in *GetEvidenceRequest, opts ...grpc.CallOption) (*GetEvidenceResponse, error)
	GetAdditionalEvidence(ctx context.Context, in *GetAdditionalEvidenceRequest, opts ...grpc.CallOption) (*GetEvidenceResponse, error)
	GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error)
	ExtendRuntimeMeasurement(ctx context.Context, in *ExtendRuntimeMeasurementRequest, opts ...grpc.CallOption) (*ExtendRuntimeMeasurementResponse, error)
	BindInitData(ctx context.Context, in *BindInitDataRequest, opts ...grpc.CallOption) (*BindInitDataResponse, error)
	GetTeeType(ctx context.Context, in *GetTeeTypeRequest, opts ...grpc.CallOption) (*GetTeeTypeResponse, error)
}

type attestationAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAttestationAgentServiceClient(cc grpc.ClientConnInterface) AttestationAgentServiceClient {
	return &attestationAgentServiceClient{cc}
}

func (c *attestationAgentServiceClient) GetEvidence(ctx context.Context, in *GetEvidenceRequest, opts ...grpc.CallOption) (*GetEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEvidenceResponse)
	err := c.cc.Invoke(ctx, AttestationAgentService_GetEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentServiceClient) GetAdditionalEvidence(ctx context.Context, in *GetAdditionalEvidenceRequest, opts ...grpc.CallOption) (*GetEvidenceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEvidenceResponse)
	err := c.cc.Invoke(ctx, AttestationAgentService_GetAdditionalEvidence_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentServiceClient) GetToken(ctx context.Context, in *GetTokenRequest, opts ...grpc.CallOption) (*GetTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTokenResponse)
	err := c.cc.Invoke(ctx, AttestationAgentService_GetToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentServiceClient) ExtendRuntimeMeasurement(ctx context.Context, in *ExtendRuntimeMeasurementRequest, opts ...grpc.CallOption) (*ExtendRuntimeMeasurementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendRuntimeMeasurementResponse)
	err := c.cc.Invoke(ctx, AttestationAgentService_ExtendRuntimeMeasurement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentServiceClient) BindInitData(ctx context.Context, in *BindInitDataRequest, opts ...grpc.CallOption) (*BindInitDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindInitDataResponse)
	err := c.cc.Invoke(ctx, AttestationAgentService_BindInitData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *attestationAgentServiceClient) GetTeeType(ctx context.Context, in *GetTeeTypeRequest, opts ...grpc.CallOption) (*GetTeeTypeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTeeTypeResponse)
	err := c.cc.Invoke(ctx, AttestationAgentService_GetTeeType_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AttestationAgentServiceServer is the server API for AttestationAgentService service.
// All implementations must embed UnimplementedAttestationAgentServiceServer
// for forward compatibility.
type AttestationAgentServiceServer interface {
	GetEvidence(context.Context, *GetEvidenceRequest) (*GetEvidenceResponse, error)
	GetAdditionalEvidence(context.Context, *GetAdditionalEvidenceRequest) (*GetEvidenceResponse, error)
	GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error)
	ExtendRuntimeMeasurement(context.Context, *ExtendRuntimeMeasurementRequest) (*ExtendRuntimeMeasurementResponse, error)
	BindInitData(context.Context, *BindInitDataRequest) (*BindInitDataResponse, error)
	GetTeeType(context.Context, *GetTeeTypeRequest) (*GetTeeTypeResponse, error)
	mustEmbedUnimplementedAttestationAgentServiceServer()
}

// UnimplementedAttestationAgentServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAttestationAgentServiceServer struct{}

func (UnimplementedAttestationAgentServiceServer) GetEvidence(context.Context, *GetEvidenceRequest) (*GetEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEvidence not implemented")
}
func (UnimplementedAttestationAgentServiceServer) GetAdditionalEvidence(context.Context, *GetAdditionalEvidenceRequest) (*GetEvidenceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdditionalEvidence not implemented")
}
func (UnimplementedAttestationAgentServiceServer) GetToken(context.Context, *GetTokenRequest) (*GetTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetToken not implemented")
}
func (UnimplementedAttestationAgentServiceServer) ExtendRuntimeMeasurement(context.Context, *ExtendRuntimeMeasurementRequest) (*ExtendRuntimeMeasurementResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ExtendRuntimeMeasurement not implemented")
}
func (UnimplementedAttestationAgentServiceServer) BindInitData(context.Context, *BindInitDataRequest) (*BindInitDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BindInitData not implemented")
}
func (UnimplementedAttestationAgentServiceServer) GetTeeType(context.Context, *GetTeeTypeRequest) (*GetTeeTypeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTeeType not implemented")
}
func (UnimplementedAttestationAgentServiceServer) mustEmbedUnimplementedAttestationAgentServiceServer() {
}
func (UnimplementedAttestationAgentServiceServer) testEmbeddedByValue() {}

// UnsafeAttestationAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AttestationAgentServiceServer will
// result in compilation errors.
type UnsafeAttestationAgentServiceServer interface {
	mustEmbedUnimplementedAttestationAgentServiceServer()
}

func RegisterAttestationAgentServiceServer(s grpc.ServiceRegistrar, srv AttestationAgentServiceServer) {
	// If the following call panics, it indicates UnimplementedAttestationAgentServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AttestationAgentService_ServiceDesc, srv)
}

func _AttestationAgentService_GetEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServiceServer).GetEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgentService_GetEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServiceServer).GetEvidence(ctx, req.(*GetEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgentService_GetAdditionalEvidence_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdditionalEvidenceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServiceServer).GetAdditionalEvidence(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgentService_GetAdditionalEvidence_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServiceServer).GetAdditionalEvidence(ctx, req.(*GetAdditionalEvidenceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgentService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTokenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgentService_GetToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServiceServer).GetToken(ctx, req.(*GetTokenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgentService_ExtendRuntimeMeasurement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendRuntimeMeasurementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServiceServer).ExtendRuntimeMeasurement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgentService_ExtendRuntimeMeasurement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServiceServer).ExtendRuntimeMeasurement(ctx, req.(*ExtendRuntimeMeasurementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgentService_BindInitData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindInitDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServiceServer).BindInitData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgentService_BindInitData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServiceServer).BindInitData(ctx, req.(*BindInitDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AttestationAgentService_GetTeeType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTeeTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AttestationAgentServiceServer).GetTeeType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AttestationAgentService_GetTeeType_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AttestationAgentServiceServer).GetTeeType(ctx, req.(*GetTeeTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AttestationAgentService_ServiceDesc is the grpc.ServiceDesc for AttestationAgentService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AttestationAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "attestation_agent.AttestationAgentService",
	HandlerType: (*AttestationAgentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetEvidence",
			Handler:    _AttestationAgentService_GetEvidence_Handler,
		},
		{
			MethodName: "GetAdditionalEvidence",
			Handler:    _AttestationAgentService_GetAdditionalEvidence_Handler,
		},
		{
			MethodName: "GetToken",
			Handler:    _AttestationAgentService_GetToken_Handler,
		},
		{
			MethodName: "ExtendRuntimeMeasurement",
			Handler:    _AttestationAgentService_ExtendRuntimeMeasurement_Handler,
		},
		{
			MethodName: "BindInitData",
			Handler:    _AttestationAgentService_BindInitData_Handler,
		},
		{
			MethodName: "GetTeeType",
			Handler:    _AttestationAgentService_GetTeeType_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "internal/proto/attestation-agent/attestation-agent.proto",
}
