// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: internal/proto/attestation-agent/attestation-agent.proto

package attestation_agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RuntimeMeasurementResult int32

const (
	RuntimeMeasurementResult_OK            RuntimeMeasurementResult = 0
	RuntimeMeasurementResult_NOT_SUPPORTED RuntimeMeasurementResult = 1
	RuntimeMeasurementResult_NOT_ENABLED   RuntimeMeasurementResult = 2
)

// Enum value maps for RuntimeMeasurementResult.
var (
	RuntimeMeasurementResult_name = map[int32]string{
		0: "OK",
		1: "NOT_SUPPORTED",
		2: "NOT_ENABLED",
	}
	RuntimeMeasurementResult_value = map[string]int32{
		"OK":            0,
		"NOT_SUPPORTED": 1,
		"NOT_ENABLED":   2,
	}
)

func (x RuntimeMeasurementResult) Enum() *RuntimeMeasurementResult {
	p := new(RuntimeMeasurementResult)
	*p = x
	return p
}

func (x RuntimeMeasurementResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RuntimeMeasurementResult) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_proto_attestation_agent_attestation_agent_proto_enumTypes[0].Descriptor()
}

func (RuntimeMeasurementResult) Type() protoreflect.EnumType {
	return &file_internal_proto_attestation_agent_attestation_agent_proto_enumTypes[0]
}

func (x RuntimeMeasurementResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RuntimeMeasurementResult.Descriptor instead.
func (RuntimeMeasurementResult) EnumDescriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{0}
}

// Get the primary evidence from the guest.
type GetEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeData   []byte                 `protobuf:"bytes,1,opt,name=RuntimeData,proto3" json:"RuntimeData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvidenceRequest) Reset() {
	*x = GetEvidenceRequest{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvidenceRequest) ProtoMessage() {}

func (x *GetEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvidenceRequest.ProtoReflect.Descriptor instead.
func (*GetEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{0}
}

func (x *GetEvidenceRequest) GetRuntimeData() []byte {
	if x != nil {
		return x.RuntimeData
	}
	return nil
}

type GetAdditionalEvidenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RuntimeData   []byte                 `protobuf:"bytes,1,opt,name=RuntimeData,proto3" json:"RuntimeData,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAdditionalEvidenceRequest) Reset() {
	*x = GetAdditionalEvidenceRequest{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAdditionalEvidenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAdditionalEvidenceRequest) ProtoMessage() {}

func (x *GetAdditionalEvidenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAdditionalEvidenceRequest.ProtoReflect.Descriptor instead.
func (*GetAdditionalEvidenceRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{1}
}

func (x *GetAdditionalEvidenceRequest) GetRuntimeData() []byte {
	if x != nil {
		return x.RuntimeData
	}
	return nil
}

type GetEvidenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Evidence      []byte                 `protobuf:"bytes,1,opt,name=Evidence,proto3" json:"Evidence,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetEvidenceResponse) Reset() {
	*x = GetEvidenceResponse{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetEvidenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetEvidenceResponse) ProtoMessage() {}

func (x *GetEvidenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetEvidenceResponse.ProtoReflect.Descriptor instead.
func (*GetEvidenceResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{2}
}

func (x *GetEvidenceResponse) GetEvidence() []byte {
	if x != nil {
		return x.Evidence
	}
	return nil
}

type GetTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenType     string                 `protobuf:"bytes,1,opt,name=TokenType,proto3" json:"TokenType,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenRequest) Reset() {
	*x = GetTokenRequest{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenRequest) ProtoMessage() {}

func (x *GetTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenRequest.ProtoReflect.Descriptor instead.
func (*GetTokenRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{3}
}

func (x *GetTokenRequest) GetTokenType() string {
	if x != nil {
		return x.TokenType
	}
	return ""
}

type GetTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         []byte                 `protobuf:"bytes,1,opt,name=Token,proto3" json:"Token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenResponse) Reset() {
	*x = GetTokenResponse{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenResponse) ProtoMessage() {}

func (x *GetTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenResponse.ProtoReflect.Descriptor instead.
func (*GetTokenResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{4}
}

func (x *GetTokenResponse) GetToken() []byte {
	if x != nil {
		return x.Token
	}
	return nil
}

// Extend the dynamic/runtime measurement with given materials. This would change the state
// of current TEE's status, e.g. TDX's RTMR, (v)TPM's PCR, by adding a record in eventlog.
type ExtendRuntimeMeasurementRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The domain to which this event entry belongs. This domain is used to distinguish the semantics of log entries in different contexts.
	Domain string `protobuf:"bytes,1,opt,name=Domain,proto3" json:"Domain,omitempty"`
	// Concrete operation type that this event entry records.
	Operation string `protobuf:"bytes,2,opt,name=Operation,proto3" json:"Operation,omitempty"`
	// Detailed content of the operation that this event entry records.
	Content string `protobuf:"bytes,3,opt,name=Content,proto3" json:"Content,omitempty"`
	// Which PCR will be extended with the hash of this entry.
	RegisterIndex *uint64 `protobuf:"varint,4,opt,name=RegisterIndex,proto3,oneof" json:"RegisterIndex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRuntimeMeasurementRequest) Reset() {
	*x = ExtendRuntimeMeasurementRequest{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRuntimeMeasurementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRuntimeMeasurementRequest) ProtoMessage() {}

func (x *ExtendRuntimeMeasurementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRuntimeMeasurementRequest.ProtoReflect.Descriptor instead.
func (*ExtendRuntimeMeasurementRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ExtendRuntimeMeasurementRequest) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ExtendRuntimeMeasurementRequest) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *ExtendRuntimeMeasurementRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ExtendRuntimeMeasurementRequest) GetRegisterIndex() uint64 {
	if x != nil && x.RegisterIndex != nil {
		return *x.RegisterIndex
	}
	return 0
}

type ExtendRuntimeMeasurementResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Result        RuntimeMeasurementResult `protobuf:"varint,1,opt,name=Result,proto3,enum=attestation_agent.RuntimeMeasurementResult" json:"Result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendRuntimeMeasurementResponse) Reset() {
	*x = ExtendRuntimeMeasurementResponse{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendRuntimeMeasurementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendRuntimeMeasurementResponse) ProtoMessage() {}

func (x *ExtendRuntimeMeasurementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendRuntimeMeasurementResponse.ProtoReflect.Descriptor instead.
func (*ExtendRuntimeMeasurementResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ExtendRuntimeMeasurementResponse) GetResult() RuntimeMeasurementResult {
	if x != nil {
		return x.Result
	}
	return RuntimeMeasurementResult_OK
}

type BindInitDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Digest        []byte                 `protobuf:"bytes,1,opt,name=Digest,proto3" json:"Digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindInitDataRequest) Reset() {
	*x = BindInitDataRequest{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindInitDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindInitDataRequest) ProtoMessage() {}

func (x *BindInitDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindInitDataRequest.ProtoReflect.Descriptor instead.
func (*BindInitDataRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{7}
}

func (x *BindInitDataRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type BindInitDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindInitDataResponse) Reset() {
	*x = BindInitDataResponse{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindInitDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindInitDataResponse) ProtoMessage() {}

func (x *BindInitDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindInitDataResponse.ProtoReflect.Descriptor instead.
func (*BindInitDataResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{8}
}

type GetTeeTypeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeeTypeRequest) Reset() {
	*x = GetTeeTypeRequest{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeeTypeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeeTypeRequest) ProtoMessage() {}

func (x *GetTeeTypeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeeTypeRequest.ProtoReflect.Descriptor instead.
func (*GetTeeTypeRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{9}
}

type GetTeeTypeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tee           string                 `protobuf:"bytes,1,opt,name=tee,proto3" json:"tee,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTeeTypeResponse) Reset() {
	*x = GetTeeTypeResponse{}
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTeeTypeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTeeTypeResponse) ProtoMessage() {}

func (x *GetTeeTypeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTeeTypeResponse.ProtoReflect.Descriptor instead.
func (*GetTeeTypeResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP(), []int{10}
}

func (x *GetTeeTypeResponse) GetTee() string {
	if x != nil {
		return x.Tee
	}
	return ""
}

var File_internal_proto_attestation_agent_attestation_agent_proto protoreflect.FileDescriptor

const file_internal_proto_attestation_agent_attestation_agent_proto_rawDesc = "" +
	"\n" +
	"8internal/proto/attestation-agent/attestation-agent.proto\x12\x11attestation_agent\"6\n" +
	"\x12GetEvidenceRequest\x12 \n" +
	"\vRuntimeData\x18\x01 \x01(\fR\vRuntimeData\"@\n" +
	"\x1cGetAdditionalEvidenceRequest\x12 \n" +
	"\vRuntimeData\x18\x01 \x01(\fR\vRuntimeData\"1\n" +
	"\x13GetEvidenceResponse\x12\x1a\n" +
	"\bEvidence\x18\x01 \x01(\fR\bEvidence\"/\n" +
	"\x0fGetTokenRequest\x12\x1c\n" +
	"\tTokenType\x18\x01 \x01(\tR\tTokenType\"(\n" +
	"\x10GetTokenResponse\x12\x14\n" +
	"\x05Token\x18\x01 \x01(\fR\x05Token\"\xae\x01\n" +
	"\x1fExtendRuntimeMeasurementRequest\x12\x16\n" +
	"\x06Domain\x18\x01 \x01(\tR\x06Domain\x12\x1c\n" +
	"\tOperation\x18\x02 \x01(\tR\tOperation\x12\x18\n" +
	"\aContent\x18\x03 \x01(\tR\aContent\x12)\n" +
	"\rRegisterIndex\x18\x04 \x01(\x04H\x00R\rRegisterIndex\x88\x01\x01B\x10\n" +
	"\x0e_RegisterIndex\"g\n" +
	" ExtendRuntimeMeasurementResponse\x12C\n" +
	"\x06Result\x18\x01 \x01(\x0e2+.attestation_agent.RuntimeMeasurementResultR\x06Result\"-\n" +
	"\x13BindInitDataRequest\x12\x16\n" +
	"\x06Digest\x18\x01 \x01(\fR\x06Digest\"\x16\n" +
	"\x14BindInitDataResponse\"\x13\n" +
	"\x11GetTeeTypeRequest\"&\n" +
	"\x12GetTeeTypeResponse\x12\x10\n" +
	"\x03tee\x18\x01 \x01(\tR\x03tee*F\n" +
	"\x18RuntimeMeasurementResult\x12\x06\n" +
	"\x02OK\x10\x00\x12\x11\n" +
	"\rNOT_SUPPORTED\x10\x01\x12\x0f\n" +
	"\vNOT_ENABLED\x10\x022\x8c\x05\n" +
	"\x17AttestationAgentService\x12^\n" +
	"\vGetEvidence\x12%.attestation_agent.GetEvidenceRequest\x1a&.attestation_agent.GetEvidenceResponse\"\x00\x12r\n" +
	"\x15GetAdditionalEvidence\x12/.attestation_agent.GetAdditionalEvidenceRequest\x1a&.attestation_agent.GetEvidenceResponse\"\x00\x12U\n" +
	"\bGetToken\x12\".attestation_agent.GetTokenRequest\x1a#.attestation_agent.GetTokenResponse\"\x00\x12\x85\x01\n" +
	"\x18ExtendRuntimeMeasurement\x122.attestation_agent.ExtendRuntimeMeasurementRequest\x1a3.attestation_agent.ExtendRuntimeMeasurementResponse\"\x00\x12a\n" +
	"\fBindInitData\x12&.attestation_agent.BindInitDataRequest\x1a'.attestation_agent.BindInitDataResponse\"\x00\x12[\n" +
	"\n" +
	"GetTeeType\x12$.attestation_agent.GetTeeTypeRequest\x1a%.attestation_agent.GetTeeTypeResponse\"\x00BSZQgithub.com/ultravioletrs/cocos/internal/proto/attestation-agent;attestation_agentb\x06proto3"

var (
	file_internal_proto_attestation_agent_attestation_agent_proto_rawDescOnce sync.Once
	file_internal_proto_attestation_agent_attestation_agent_proto_rawDescData []byte
)

func file_internal_proto_attestation_agent_attestation_agent_proto_rawDescGZIP() []byte {
	file_internal_proto_attestation_agent_attestation_agent_proto_rawDescOnce.Do(func() {
		file_internal_proto_attestation_agent_attestation_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_attestation_agent_attestation_agent_proto_rawDesc), len(file_internal_proto_attestation_agent_attestation_agent_proto_rawDesc)))
	})
	return file_internal_proto_attestation_agent_attestation_agent_proto_rawDescData
}

var file_internal_proto_attestation_agent_attestation_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_internal_proto_attestation_agent_attestation_agent_proto_goTypes = []any{
	(RuntimeMeasurementResult)(0),            // 0: attestation_agent.RuntimeMeasurementResult
	(*GetEvidenceRequest)(nil),               // 1: attestation_agent.GetEvidenceRequest
	(*GetAdditionalEvidenceRequest)(nil),     // 2: attestation_agent.GetAdditionalEvidenceRequest
	(*GetEvidenceResponse)(nil),              // 3: attestation_agent.GetEvidenceResponse
	(*GetTokenRequest)(nil),                  // 4: attestation_agent.GetTokenRequest
	(*GetTokenResponse)(nil),                 // 5: attestation_agent.GetTokenResponse
	(*ExtendRuntimeMeasurementRequest)(nil),  // 6: attestation_agent.ExtendRuntimeMeasurementRequest
	(*ExtendRuntimeMeasurementResponse)(nil), // 7: attestation_agent.ExtendRuntimeMeasurementResponse
	(*BindInitDataRequest)(nil),              // 8: attestation_agent.BindInitDataRequest
	(*BindInitDataResponse)(nil),             // 9: attestation_agent.BindInitDataResponse
	(*GetTeeTypeRequest)(nil),                // 10: attestation_agent.GetTeeTypeRequest
	(*GetTeeTypeResponse)(nil),               // 11: attestation_agent.GetTeeTypeResponse
}
var file_internal_proto_attestation_agent_attestation_agent_proto_depIdxs = []int32{
	0,  // 0: attestation_agent.ExtendRuntimeMeasurementResponse.Result:type_name -> attestation_agent.RuntimeMeasurementResult
	1,  // 1: attestation_agent.AttestationAgentService.GetEvidence:input_type -> attestation_agent.GetEvidenceRequest
	2,  // 2: attestation_agent.AttestationAgentService.GetAdditionalEvidence:input_type -> attestation_agent.GetAdditionalEvidenceRequest
	4,  // 3: attestation_agent.AttestationAgentService.GetToken:input_type -> attestation_agent.GetTokenRequest
	6,  // 4: attestation_agent.AttestationAgentService.ExtendRuntimeMeasurement:input_type -> attestation_agent.ExtendRuntimeMeasurementRequest
	8,  // 5: attestation_agent.AttestationAgentService.BindInitData:input_type -> attestation_agent.BindInitDataRequest
	10, // 6: attestation_agent.AttestationAgentService.GetTeeType:input_type -> attestation_agent.GetTeeTypeRequest
	3,  // 7: attestation_agent.AttestationAgentService.GetEvidence:output_type -> attestation_agent.GetEvidenceResponse
	3,  // 8: attestation_agent.AttestationAgentService.GetAdditionalEvidence:output_type -> attestation_agent.GetEvidenceResponse
	5,  // 9: attestation_agent.AttestationAgentService.GetToken:output_type -> attestation_agent.GetTokenResponse
	7,  // 10: attestation_agent.AttestationAgentService.ExtendRuntimeMeasurement:output_type -> attestation_agent.ExtendRuntimeMeasurementResponse
	9,  // 11: attestation_agent.AttestationAgentService.BindInitData:output_type -> attestation_agent.BindInitDataResponse
	11, // 12: attestation_agent.AttestationAgentService.GetTeeType:output_type -> attestation_agent.GetTeeTypeResponse
	7,  // [7:13] is the sub-list for method output_type
	1,  // [1:7] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_internal_proto_attestation_agent_attestation_agent_proto_init() }
func file_internal_proto_attestation_agent_attestation_agent_proto_init() {
	if File_internal_proto_attestation_agent_attestation_agent_proto != nil {
		return
	}
	file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes[5].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_attestation_agent_attestation_agent_proto_rawDesc), len(file_internal_proto_attestation_agent_attestation_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_attestation_agent_attestation_agent_proto_goTypes,
		DependencyIndexes: file_internal_proto_attestation_agent_attestation_agent_proto_depIdxs,
		EnumInfos:         file_internal_proto_attestation_agent_attestation_agent_proto_enumTypes,
		MessageInfos:      file_internal_proto_attestation_agent_attestation_agent_proto_msgTypes,
	}.Build()
	File_internal_proto_attestation_agent_attestation_agent_proto = out.File
	file_internal_proto_attestation_agent_attestation_agent_proto_goTypes = nil
	file_internal_proto_attestation_agent_attestation_agent_proto_depIdxs = nil
}
