global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'cocos-manager'
    static_configs:
      - targets: ['192.168.100.4:7003']  # Adjust to your manager http port
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s
